name: Portfolio
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build portfolio images
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-images:${{ github.run_number }} .
            docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-images .

      - name: Push image to Docker Hub
        run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-images:${{ github.run_number }}
            docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-images

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          #port: ${{ secrets.SERVER_PORT }}
          script: |
            docker rm -f portfolio || true
            docker run -d --name portfolio -p 8080:5001 ${{ secrets.DOCKER_USERNAME }}/portfolio-images:${{ github.run_number }}
